FT-1293/Add simple publisher
doofinder/events_manager pull request #17
Opened 2022-01-24 15:20 UTC by joaq-dfnder

Needed by dfOctopus for [FT-1293](https://doofinder.atlassian.net/browse/FT-1293).

The idea is to add a publisher to go alongside the consumer, for use in Elixir projects that need to trigger events. This is already needed in dfOctopus, as part of [FT-1253](https://doofinder.atlassian.net/browse/FT-1253): dfOctopus can alter the DB directly, so it needs to be able to notify LiveLayer about these changes.

The publisher is very simple, just opening a connection for each message sent.

2022-01-24 15:43 UTC, alvanieto requested changes

2022-01-24 15:43 UTC, alvanieto commented on lib/events_manager/publisher.ex
> +  @amqp_module if Mix.env() == :test, do: AMQPMock, else: AMQP
Move this to config/test.exs and config/config.exs

2022-01-24 15:43 UTC, alvanieto commented on lib/events_manager/publisher.ex
> +    with {:ok, {conn, chan}} <- open_channel(uri_or_options),
Will we need bulk operations?

2022-01-24 16:26 UTC, agutierrezrodriguez commented on lib/events_manager/consumer.ex
> +  @amqp_module Application.compile_env(:events_manager, :amqp_module)
This is an error. Please revert

https://hexdocs.pm/elixir/main/library-guidelines.html#avoid-application-configuration

2022-01-24 16:27 UTC, joaq-dfnder commented on lib/events_manager/publisher.ex
> +  @amqp_module if Mix.env() == :test, do: AMQPMock, else: AMQP
Done.

2022-01-24 16:27 UTC, agutierrezrodriguez commented on lib/events_manager/publisher.ex
> +  @spec send_to_queue(String.t() | keyword(), String.t(), String.t()) :: :ok | {:error, any()}
what usecases we will have to send a message to a queue?
Events always should be sent to "Exchanges"

2022-01-24 16:28 UTC, joaq-dfnder commented on lib/events_manager/publisher.ex
> +    with {:ok, {conn, chan}} <- open_channel(uri_or_options),
Changes to a Layer will require updating all of its screens, for as long as we're duplicating options at both the screen and the layer level.
Other than that, I can't foresee other bulk operations.

2022-01-24 16:56 UTC, alvanieto commented on lib/events_manager/publisher.ex
> +  @amqp_module if Mix.env() == :test, do: AMQPMock, else: AMQP
@agutierrezrodriguez  what's the best way to deal with configuration in libraries?
get_env with a default value?
System.get_env("AMQP_BACKEND", AMQP)?

2022-01-24 17:48 UTC, agutierrezrodriguez commented on lib/events_manager/publisher.ex
> +  @amqp_module if Mix.env() == :test, do: AMQPMock, else: AMQP
[get_env but from application.](https://hexdocs.pm/elixir/1.12/Application.html#get_env/3)

In that case, Application.get_env is not applicable because is a testing mock.

2022-01-25 09:09 UTC, joaq-dfnder commented on lib/events_manager/publisher.ex
> +defmodule EventsManager.Publisher do
Do you mean that `EventsManager.Publisher` should become `Publisher` and move from `lib/events_manager/publisher.ex` to `lib/publisher.ex`?

2022-01-25 09:15 UTC, joaq-dfnder commented on lib/events_manager/publisher.ex
> +  @spec send_to_queue(String.t() | keyword(), String.t(), String.t()) :: :ok | {:error, any()}
I was replicating the functionality of the `RabbitMQClient` we have in Helpapp. In there, sending to queue is used only to send tasks to dftasks. I don't think we'll need this functionality for now so it could be deleted, or we could let it be just in case we need it later.

2022-01-25 09:16 UTC, joaq-dfnder commented on lib/events_manager/publisher.ex
> +  Send a `payload` dirctly to a `queue`, connecting to the host specified
Done.

2022-01-25 09:16 UTC, joaq-dfnder commented on lib/events_manager/consumer.ex
> +  @amqp_module Application.compile_env(:events_manager, :amqp_module)
Done.

2022-01-25 09:16 UTC, joaq-dfnder commented on lib/events_manager/publisher.ex
> +  @amqp_module Application.compile_env(:events_manager, :amqp_module)
Done.

2022-01-25 09:43 UTC, alvanieto approved these changes

2022-01-25 16:20 UTC, agutierrezrodriguez commented on lib/events_manager/publisher.ex
> +  @spec send_to_queue(String.t() | keyword(), String.t(), String.t()) :: :ok | {:error, any()}
You can delete it. The sendind tasks feature is in https://github.com/doofinder/dftasks_publisher/

2022-01-25 16:55 UTC, joaq-dfnder commented on lib/events_manager/publisher.ex
> +  @spec send_to_queue(String.t() | keyword(), String.t(), String.t()) :: :ok | {:error, any()}
Done.

2022-01-25 16:56 UTC, joaq-dfnder commented on lib/events_manager/publisher.ex
> +defmodule EventsManager.Publisher do
Done.

2022-01-25 17:34 UTC, agutierrezrodriguez approved these changes
nice!

2022-01-26 09:49 UTC, merged